CREATE TABLE Ecommerce (
    fullVisitorId VARCHAR(255) NOT NULL,
    channelGrouping VARCHAR(255),
    time INTERVAL,
    country VARCHAR(255),
    city VARCHAR(255),
    totalTransactionRevenue FLOAT,
    transactions INT,
    timeOnSite INTERVAL,
    pageviews INT,
    sessionQualityDim INT,
    date DATE,
    visitId VARCHAR(255),
    type VARCHAR(255),
    productRefundAmount FLOAT,
    productQuantity INT,
    productPrice FLOAT,
    productRevenue FLOAT,
    productSKU VARCHAR(255),
    v2ProductName VARCHAR(255),
    v2ProductCategory VARCHAR(255),
    productVariant VARCHAR(255),
    currencyCode VARCHAR(255),
    itemQuantity INT,
    itemRevenue FLOAT,
    transactionRevenue FLOAT,
    transactionId VARCHAR(255),
    pageTitle VARCHAR(255),
    searchKeyword VARCHAR(255),
    pagePathLevel1 VARCHAR(255),
    eCommerceAction_type INT,
    eCommerceAction_step INT,
    eCommerceAction_option VARCHAR(255)
);